### ISSUE TITLE
No such file or directory: 'README.md'

### ISSUE THREAD

**Issue by andreashhpetersen** [discolabs/django-shopify-webhook#1]
I have an app that I want to use this package on, but I get this error while deploying to Heroku:

> remote:       Collecting django-shopify-webhook==0.2.6 (from -r requirements.txt (line 6))
> remote:          Downloading django-shopify-webhook-0.2.6.tar.gz
> remote:            Complete output from command python setup.py egg_info:
> remote:            Traceback (most recent call last):
> remote:              File "<string>", line 1, in <module>
> remote:              File "/tmp/pip-build-C6lNSH/django-shopify-webhook/setup.py", line 9, in <module>
> remote:                long_description = open('README.md').read(),
> remote:            IOError: [Errno 2] No such file or directory: 'README.md'
> remote:            
> remote:            ----------------------------------------
> remote:        Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-C6lNSH/django-shopify-webhook

I can see that in MANIFEST.in it says to include README.rst and not README.md - is this the issue and how would I fix it?

**Comment by gavinballard** [comment]
@andreashhpetersen You're right, this looks like an issue with the packaging. I'll fix this up and push a new version of the package shortly.

**Comment by andreashhpetersen** [comment]
@gavinballard Thanks so much, it would be much needed! This Shopify webhook-thing is bugging the hell out of me...

**Comment by gavinballard** [comment]
I've pushed a fix for this and released a new version of the package - `0.3.0`. You should be able to install that fine.

**Comment by andreashhpetersen** [comment]
Thanks a lot! I can download and install it properly and I get no errors when deploying to Heroku.

However, I now get a "No module named views"-error, which is triggered when I try to import 'shopify_webhook.views' in urls.py.

Am I doing this wrong? Am I not suppose to add 'shopify_webhook' to INSTALLED_APPS and import the WebhookView from 'shopify_webhook.views' in urls.py?

**Comment by gavinballard** [comment]
You should have something like this in your `urls.py`:

```
from django.conf.urls import patterns, include, url
from shopify_webhook.views import WebhookView

urlpatterns = patterns('',
    url(r'webhook/', WebhookView.as_view(), name = 'webhook'),
)
```

**Comment by andreashhpetersen** [comment]
I believe I have but I still get the error..

```
 16 from django.conf.urls import patterns, include, url
 17 from django.conf import settings
 18 from django.contrib import admin
 19 from django.conf.urls.static import static
 20 from django.views.decorators.csrf import csrf_exempt
 21 
 22 from my_app import views
 23 from shopify_webhook.views import WebhookView
 24 
 25 urlpatterns = patterns('',
 26         url(r'^$', views.home, name='home'),
 27         url(r'^order/', WebhookView.as_view(), name='order'),
 28         url(r'^login/', include('shopify_auth.urls')),
 29         url(r'^accounts/login/$', include('shopify_auth.urls')),
 30         url(r'^eksporter/', include('my_app.urls')),
 31 )
```

**Comment by gavinballard** [comment]
Can you let me know what version of Python + Django you're using?

**Comment by andreashhpetersen** [comment]
Yes, I am using Python 2.7 and Django 1.9.2 (my Django was updated from 1.8.5 when I installed v0.3.0 of this package)

**Comment by gavinballard** [comment]
Thanks - do you know which patch version of Python? 2.7.x?

**Comment by andreashhpetersen** [comment]
My console tells me its Python 2.7.10

**Comment by gavinballard** [comment]
@andreashhpetersen, I set up a brand new Django 1.9.2 app with Python 2.7.10 and added the webhooks package to `INSTALLED_APPS`. I was then able to import the view for use an an URL okay. See here: https://github.com/gavinballard/webhook_example.

I'm afraid I don't have the time to dig into this a little bit deeper, hopefully it's just a quirk of how your app is set up that can be resolved. Good luck!
